version: 'V1.0.6'
# Rolled back from v7 to v6 as requested by jade

services:

# Importer & Reporter

  fileimport:
    image: next3pl.azurecr.io/next3pl-ftp-importer:V1.0.2-ir
    ports: 
      - 3383:3001
    networks:
      coreapp_subnet:
        ipv4_address: 172.33.1.24
    volumes:
      - /pwdocker/irconfig:/irconfig
    environment:
    - SEND_FILE_TO_IMPORT_RABBITQ_CONN= amqp://172.33.1.27:5672    
    - HTTP= http://172.33.1.24:3001/api/ftp/fileImporter
    - TZ=Australia/Sydney
    
  fileprocess:    
    image: next3pl.azurecr.io/next3pl-ftp-processor:V1.0.2-ir
    ports: 
      - 3384:3002
    networks:
      coreapp_subnet:
        ipv4_address: 172.33.1.25
    volumes:
      - /pwdocker/irconfig:/irconfig
    environment:
      - RECEIVE_FILE_TO_IMPORT_RABBITQ_CONN= amqp://172.33.1.27:5672
      - SEND_FILE_TO_CUSTOMERPORTAL_RABBITQ_CONN= amqp://172.33.1.27:5672
      - HTTP = http://devapisrv:9006/api/mq/readmessages
      - callImport_URL = http://172.33.1.24:3001
      - TZ=Australia/Sydney
  
  ir:
    image: next3pl.azurecr.io/importerreporter:V1.0.2-ir
    ports:
      - 3385:4200
    networks:
      coreapp_subnet:
        ipv4_address: 172.33.1.26
    volumes:
      - /pwdocker/irconfig:/usr/share/nginx/html/assets/config
    environment:
        - TZ=Australia/Sydney
  
  irrabbit:
    image: rabbitmq:3-management
    ports:
     - 15672:15672   
     - 5672:5672
    networks:
      coreapp_subnet:
        ipv4_address: 172.33.1.27
    environment:
        - TZ=Australia/Sydney

networks:
 coreapp_subnet:
  driver: bridge
  ipam:
   config:
    - subnet: 172.33.1.0/24
